name: Sanity Deploy
on:
  push:
    paths:
      - "studio/**"
env:
  SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
jobs:
  deploy:
    name: Deploy Sanity
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: studio/
    steps:
      - uses: actions/checkout@v2
      - uses: sanity-io/github-action-sanity@v0.2-alpha
        with:
          args: deploy
